my/my/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('weather/',include('weather.urls')),
    path('timetable/',include('timetable.urls')),
    path('success/',include('success.urls')),
    path('api/',include('myApiAll.urls'))
]

my/success/urls.py
from django.urls import path
from .views import sucs, DesiresList, GoalsMy, tasks, task_up



urlpatterns = [
    path('', sucs, name='success' ),
    path('desires', DesiresList.as_view(), name='desires'),
    path('goals', GoalsMy.as_view(), name='goals'),
    path('tasks', tasks, name='tasks'),
    path('tasks/<int:pk>', task_up, name='task_up'),

]

my/success/models.py
from django.db import models
from django.contrib.auth.models import User

class Desires(models.Model):
    contect = models.TextField(max_length=300)
    user_id = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    create_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user_id} хочу {self.contect}'

class Goals(models.Model):
    context = models.CharField(max_length=100)
    user_id = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    create_at = models.DateField(auto_now_add=True)


class PriorityTask(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}  tasks {self.pk}'

class KindTask(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name}  tasks'


class Task(models.Model):
    text = models.CharField(max_length=10)
    priority = models.ForeignKey(PriorityTask,on_delete=models.PROTECT,verbose_name='priority')
    kind = models.ForeignKey(KindTask,on_delete=models.PROTECT,verbose_name='kind')
    is_do = models.BooleanField(default=False,verbose_name='have done?')
    user_id = models.ForeignKey(User,verbose_name='Кто автор', on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return f'{self.text}'

my/success/forms.py
from .models import Task
from django import forms

class GoalsForm(forms.Form):
    context = forms.CharField(max_length=100,label='Твои цели',widget=forms.TextInput(attrs={'class': 'form-control'}))

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text', 'priority', 'kind']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
            'kind': forms.Select(attrs={'class': 'form-control'}),
        }

my/success/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Desires, Task, Goals
from .forms import TaskForm
from django.views import View
from django.contrib import messages



class DesiresList(ListView):
    model = Desires
    template_name = 'success/desires.html'
    context_object_name = 'desires'


class GoalsMy(View):
    template_name = 'success/goals.html'

    def get(self, request):
        goals = Goals.objects.filter(user_id=request.user.id)
        con = {
            'goals': goals
        }
        return render(request, self.template_name, con)


def tasks(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Task.objects.create(
                text=data['text'],
                priority=data['priority'],
                kind=data['kind'],
                user_id=request.user
            )
            messages.success(request, 'task added')
            return redirect('success')
        else:
            messages.error(request, 'oops')

    urgent_work_tasks = Task.objects.filter(user_id=request.user.id, kind_id=2, priority_id=1)
    n_urgent_work_tasks = Task.objects.filter(user_id=request.user.id, kind_id=2, priority_id=2)
    n_important_work_tasks = Task.objects.filter(user_id=request.user.id, kind_id=2, priority_id=3)
    urgent_personal_tasks = Task.objects.filter(user_id=request.user.id, kind_id=1, priority_id=1)
    n_urgent_personal_tasks = Task.objects.filter(user_id=request.user.id, kind_id=1, priority_id=2)
    n_important_personal_tasks = Task.objects.filter(user_id=request.user.id, kind_id=1, priority_id=3)
    form = form = TaskForm()
    con = {
    'uwt': urgent_work_tasks,
    'nuwt':n_urgent_work_tasks,
    'niwt': n_important_work_tasks,
    'upt': urgent_personal_tasks,
    'nupt': n_urgent_personal_tasks,
    'nipt':n_important_personal_tasks,
    'form': form
    }
    return render(request, 'success/tasks.html', con)


def task_up(request,pk):
    task = Task.objects.get(pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            task.text = data['text']
            task.priority = data['priority']
            task.kind = data['kind']
            task.save()
            messages.success(request, 'task updated')
            return redirect('timetable')
    else:
        form = TaskForm()
    con = {
        'form': form,
        'task': task
    }
    return render(request, 'success/taskupdate.html', con)



def sucs(request):
    return render(request,'success/success.html')

my/success/templates/success/desires.html
{% extends 'base.html' %}

{% block content %}
{% for item in desires %}
<p>
    {{item}}
</p>
{% endfor %}
{% endblock %}

my/success/templates/success/goals.html
{% extends 'base.html' %}

{% block content %}
<a class="nav-link" href="#">asdafdfadsg</a>
{{goals}}
{% endblock %}

my/success/templates/success/success.html
{% extends 'base.html' %}

{% block content %}
<a class="nav-link" href="{% url 'desires' %}">DESIRES</a>
<a class="nav-link" href="{% url 'goals' %}">GOALS</a>
<a class="nav-link" href="{% url 'tasks' %}">tasks</a>
{% endblock %}

my/success/templates/success/tasks.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-4">
        <form action="{% url 'tasks' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block">добавить</button>
        </form>
    </div>
    <div class="col-lg-3">
        <h3>Personal tasks:</h3>
        <div class="list-group">
            <h4>Urgent:</h4>
            {% for task in upt %}
            <a href="{% url 'task_up' task.pk %}" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}
            <h4>Not urgent:</h4>
            {% for task in nupt %}
            <a href="{% url 'task_up' task.pk %}" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}
            <h4>Not important:</h4>
            {% for task in nipt %}
            <a href="{% url 'task_up' task.pk %}" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}
        </div>
    </div>
    <div class="col-lg-3">
        <h3>Works tasks:</h3>
        <div class="list-group">
            <h5>Urgent:</h5>
            {% for task in uwt %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}
            <h5>Not urgent:</h5>
            {% for task in nuwt %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}
            <h5>Not important:</h5>
            {% for task in niwt %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                {{task}}
            </a>
            {% endfor %}

        </div>
        {% endblock %}

my/success/templates/success/taskupdate.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col-lg-4">
        <form action="{% url 'tasks' %}" method="post">
            {% csrf_token %}
            <p><label for="id_text">Text:</label> <input value={{task.text}} type="text" name="text"
                                                         class="form-control" maxlength="10"
                                                         required="" id="id_text"></p>
            <p><label for="id_priority">Priority:</label> <select name="priority" class="form-control" required=""
                                                                  id="id_priority">
                <option value="" selected="">{{task.priority}}</option>

                <option value="1">Urgent tasks 1</option>

                <option value="2">Not urgent tasks 2</option>

                <option value="3">not important tasks 3</option>

            </select></p>
            <p><label for="id_kind">Kind:</label> <select name="kind" class="form-control" required="" id="id_kind">
                <option value="" selected="">{{task.kind}}</option>

                <option value="1">Personal tasks</option>

                <option value="2">Work tasks</option>

            </select></p>

            <button type="submit" class="btn btn-primary btn-block">изменить</button>
            <button type="button" class="btn btn-primary btn-block">удалить</button>
        </form>


        {% endblock %}